### PR TITLE
add query info to main readme

### PR DESCRIPTION
**Pull request by elof**
Took the info from the README in the query file and reformated it to fit the style of the main readme. Now adding queries to the SDK is not long under TODO :D

### CODE REVIEW

**Comment by Geeber** [comment]
LGTM. Do you want to go ahead and delete query/README.md so that it isn't duplicated in two places? My concern is that the two might accidentally diverge and cause confusion.

Also, just FYI, the Travis build failure seems like it's probably this issue: https://github.com/travis-ci/travis-ci/issues/5669 and therefore should be safe to ignore for now; looks like they're hoping to have a fix soon.

**Comment by elof** [comment]
@geeber I think that's a good idea. I'll remove the second readme.

**Comment by elof** [comment]
@Geeber let me know if you think this is ready to merge meow :)

**Comment by Geeber** [comment]
Yep LGTM.

**Pull request merged**
