### PR TITLE
4.0.0

### LINKED ISSUE #61: Keen.location.coordinates becomes invalid on Samsung Galaxy S3
Here is the code I am using to add location coordinates to the Keen Properties.

double[] coordinates = {37.5793,-122.3164}; // new Double[2];
Map<String, Object> keenProperties = new HashMap<String, Object>();
Map<String, Object> keenLocationProperties = new HashMap<String, Object>();
keenLocationProperties.put("coordinates",coordinates );
 keenProperties.put("location", keenLocationProperties);
KeenClient.client().queueEvent("activityEvents", newActivityEvent.toKeenHashMap(sequenceNumber, mPrefs.getString("tag", ""),uuid),keenProperties);

---

When using the above code on Nexus 5, the keen.location.coordinates property looks correct and the data is uploaded to Keen successfully.
However, when running on the Samsung Galaxy S3 the keen.location.coordinates property does not format as an array.  The data does not upload to Keen - I get an error message Invalidpropertyvalueerror in the return JSON from Keen.

See screenshots attached (nexus5.png, samsungS3.png).  
nexus5
samsungs3

### PR DESCRIPTION
**Pull request by dkador**
fixes #61, #73, #75, and #76

### CODE REVIEW

**Comment by Geeber** [comment]
LGTM. Should we also go ahead and fix https://github.com/keenlabs/KeenClient-Java/issues/78 as part of the 4.0 release, since it's an interface change?

**Comment by dkador** [comment]
seems reasonable. that request came in after I submitted this PR. do you see anything wrong with making that public?

**Comment by Geeber** [comment]
It makes me very slightly nervous, but given the current rate of development on this SDK it's probably fine.

**Comment by dkador** [comment]
4.0.0 is released on maven and should propagate over the next few hours.

**Pull request merged**
