### PR TITLE
Scoped keys docs

### PR DESCRIPTION
**Pull request by gorzell**
Added a bit more detail to the examples.

### CODE REVIEW

**Comment by Geeber** [comment]
Looks good, thanks! Did you by any chance test this example code, just to make sure that it works? :shipit: either way, but always nice to have that sanity check :)

**Comment by gorzell** [comment]
I did not explicitly test it, but I did look at the test case to make sure it was in line with what is happening there.  What would be the best way to test it?  Write an additional test case?

**Comment by Geeber** [comment]
A test case would be awesome. See https://github.com/keenlabs/KeenClient-Java/blob/master/core/src/test/java/io/keen/client/java/ScopedKeysTest.java. I wouldn't call it a requirement given that it's a small change, but if you've got time then go for it.

**Comment by Geeber** [comment]
You could also add some validation like what's on lines 39-45? Up to you.

**Pull request merged**
